version: '3'
services:
  # pgsqla:
  #   container_name: pgsqla
  #   image: postgres
  #   environment:
  #     # PGDATA: /var/lib/postgresql/data/pgdata
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: test1234
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - postgres-net
  #   restart: unless-stopped
  #   volumes:
  #     - ${PWD}/postgres-docker:/var/lib/postgresql/data

  core-identityserver:
    container_name: core-identityserver
    build: 
      context: ../../../
      dockerfile: Lab.Core.IdentityServer/Docker/Local/Dockerfile
    ports: 
      # - "5001:443"
      - "5001:8080"
    networks:
      - postgres-net
      # - identity-net
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerLocal
    #   - ASPNETCORE_URLS=https://+:443;http://+:80
    #   - ASPNETCORE_HTTPS_PORT=5002
    #   - ASPNETCORE_Kestrel__Certificates__Default__Password=123
    #   - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    # volumes:
    #   - ~/.aspnet/https:/https:ro

# volumes:
#   db-data:
#     external: true
networks:
  postgres-net:
    name: tulip-net
    external: true
  # identity-net: