version: '3'
services:
  core-identityserver:
    container_name: core-identityserver
    build: 
      context: ../../../
      dockerfile: Lab.Core.IdentityServer/Docker/Local/Dockerfile
    ports: 
      - "5001:8080"
    networks:
      - pgsqlnet
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
        ASPNETCORE_ENVIRONMENT: DockerLocal
networks:
  pgsqlnet:
    name: tulip-net
    external: true